サインアップ機能
shinonome-inc/backend-final-assignment-yuuki-Morita-Yuuki pull request #1
Opened 2023-06-29 15:28 UTC by shang-sin

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-13 10:11 UTC, TamanPG requested changes

2023-08-13 10:11 UTC, TamanPG commented on tweets/tests.py
> +        self.assertEquals(response.status_code, 200)
assertEqualsはPython ver2.7で廃止されているようです。
https://docs.python.org/2/library/unittest.html#deprecated-aliases
signupのtestのように最新版(assertEqual)に合わせておくことをお勧めします。
https://docs.python.org/3.11/library/unittest.html#test-cases

2023-08-14 00:08 UTC, TamanPG approved these changes

2023-08-16 07:49 UTC, Yamakou621 commented
・admin.pyにuserを登録していないので登録してください。
他は大丈夫です！

2023-08-19 02:42 UTC, merged