ログイン、ログアウト機能の実装
shinonome-inc/backend-final-assignment-yuuki-Morita-Yuuki pull request #3
Opened 2023-08-24 19:29 UTC by shang-sin

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-27 07:03 UTC, Shiota620 requested changes

2023-08-27 07:03 UTC, Shiota620 commented on accounts/views.py
まず、最終課題は[[最終課題テスト項目要件]]の「画面と機能（v2）」(*1)に従ってコーディングする必要があります。

A列はviews.pyに必要なクラス名または関数名です。
B列はテンプレートが必要かどうか。つまり、HTMLファイルが必要かどうかを表します。
C列はurl.pyをコーディングする際に参考にするエンドポイントと呼ばれるものです。
D列以降は各機能を実装する際の指示が明示されています。

まずは、これに従ってコーディングすることを意識しましょう。



(*1)https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917

2023-08-27 07:03 UTC, Shiota620 commented on accounts/views.py
> +from mysite.settings import LOGIN_REDIRECT_URL
settingsモジュールは、from django.conf import settingsからimportしてください。

2023-08-27 07:03 UTC, Shiota620 commented on templates/tweets/home.html
おそらくホーム画面を作ろうとしているのだと思うのですが、今回の仕様書とこれまでのコード内容で考えると、このファイルはプロフィール画面を表示するテンプレートにあたると思います。
ホーム画面はこの後のツイート機能で作成するので今回考える必要はありません。

記述内容に関しては問題ないですが、後にホーム画面のHTMLファイルを作成し、命名する際に困ると思われるのでこのHTMLファイルがプロフィール画面のファイルだということを明確にできる命名に変更することをおすすめします。

2023-08-27 17:57 UTC, shang-sin commented on templates/tweets/home.html
ありがとうございます。修正しました。

2023-08-27 18:21 UTC, shang-sin commented on accounts/views.py
ありがとうございます。今回LoginViewやLogoutViewについては簡単にurl.pyに記述してしまったのですが、それが問題ということでしょうか？

2023-08-28 06:30 UTC, Shiota620 requested changes

2023-08-28 06:30 UTC, Shiota620 commented on tweets/views.py
> +    template_name = "tweets/profile.html"
tweetディレクトリはツイート機能を作成する時に改めて考えると思うので特に気にする必要はないですが、一応指摘だけしておくと、ここは初めに書かれていたtemplate_name = "tweets/home.html"で合っています。

2023-08-28 06:30 UTC, Shiota620 commented on templates/tweets/profile.html
> +{%block title%}Home{% endblock %}
テンプレートについては、特に指定はありませんが、個人的にはhome.htmlとprofile.htmlのタイトルが同じなのは、少し紛らわしく感じます。

2023-08-28 06:30 UTC, Shiota620 commented on templates/tweets/profile.html
ディレクトリの階層を意識しましょう。
このプロフィール画面には現在、ログインしたユーザの名前が表示されるようになっています。
{{user.username}}はどこからデータをもってきているのかを考えるとこのファイルの正しい位置が分かると思います。

2023-08-28 06:31 UTC, Shiota620 commented on accounts/views.py
申し訳ございません。見落としてました。

基本的に、プロジェクト内のコーディングの形式は、統一することが望ましいです。
例えば、SignupViewではtemplate_nameをクラス内に記述しているのに対して、LoginViewでは、urls.pyのurlpatterns = []内に記述しています。これらのコードはほぼ同じ操作をしているはずです。これでは可読性が低下してしまうのでどちらかに統一しましょう。

2023-08-31 06:41 UTC, Shiota620 requested changes

2023-08-31 06:41 UTC, Shiota620 commented on templates/registration/login.html
最終課題レビューポイントのチェックリストによるとaccountsフォルダの中にログイン画面のhtmlがある必要があるようです。

2023-08-31 23:16 UTC, shang-sin commented on templates/registration/login.html
色々試したのですが、views.pyにクラスベースで記述してかつ、accountsフォルダの中にlogin.htmlを配置するとエラーが出てしまいます。PGのスライドには、templateのアトリビュート変更はurls.pyに記述しても構わないと書いてあるので、当初のコードのままでよろしいでしょうか。

2023-09-01 07:34 UTC, Shiota620 commented on templates/registration/login.html
urls.pyに記述するならそれでいいと思います。
しかし、それなら他のクラスのtemplate_nameも書き方を統一しましょう。
勿論限度はありますが、良いコードを書く上で重要な要素の1つに統一性があります。
統一性のないコードはチーム開発や前任者からコード引き継ぐ際に問題になります。例えば、統一性のないコードは読みづらく、理解するのに時間がかかるため、精神的な疲れから見落としや誤解などを誘発する場合があります。時にはバグの原因がこの統一性がないことだったりするようです。
少し過剰かもしれませんが、今回はWeb開発を学ぶ最終課題でありすべて自分でコーディングするので少し過剰なぐらいがちょうどいいかもしれません。
SignupView、UserProfileView、ついでにHomeViewを修正しましょう。

2023-09-03 01:55 UTC, Shiota620 reviewed
一次レビューはこれで終了です。
お疲れ様でした。

2023-09-03 05:52 UTC, kenketsu commented on templates/accounts/user_profile.html
base.htmlを継承しましょう

2023-09-03 05:52 UTC, kenketsu commented on templates/tweets/home.html
base.htmlを継承しましょう

2023-09-03 05:52 UTC, kenketsu commented on accounts/views.py
> +    template_name = "accounts/login.html"
importしたLoginViewと名称が被らないようにしましょう

# Bad
from django.contrib.auth views import LoginView
class LoginView(LoginView):

# OK
from django.contrib.auth import views as auth_views
class LoginView(auth_views.LoginView):

また、ここではtemplate_nameを指定しているだけなのでurls.pyでLoginViewのas_view()メソッドの引数に記述する形でも問題ありません。

2023-09-03 05:52 UTC, kenketsu commented on accounts/tests.py
> +        self.url = reverse("accounts:logout")
setUpでUser.objects.create_userを用いてユーザーを作成し、self.client.loginまたはself.client.force_loginでログイン処理させてからログアウトのテストを行ってください。

2023-09-03 06:27 UTC, kenketsu approved these changes

2023-09-03 06:28 UTC, merged